const SHORT_FILM_DURATION = 40;

const MAX_DISPLAY_START = 12
const MAX_DISPLAY_ADD = 3

const MID_DISPLAY = 1020
const MID_DISPLAY_START = 8
const MIN_DISPLAY_ADD = 2

const MIN_DISPLAY = 560
const MIN_DISPLAY_START = 5


module.exports = {
    SHORT_FILM_DURATION,
    MAX_DISPLAY_START,
    MAX_DISPLAY_ADD,
    MID_DISPLAY,
    MID_DISPLAY_START,
    MIN_DISPLAY_ADD,
    MIN_DISPLAY,
    MIN_DISPLAY_START

  };